version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "license-management"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11s42nm96l5gm"
s3_prefix = "license-management"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "deploymentStage=\"Dev\""
